server:
  port: 8081
spring:
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
    enabled: true

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://postgresql:5432/dev}
    #url: ${POSTGRES_URL:jdbc:postgresql://postgresql:5432/dev}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  application:
    name: ff4j-security-postgres
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

ff4j:
  webconsole:
    enable: true
    url: /ff4j-web-console
    secure: true
    username: admin
    password: ff4j