apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff4j-security
  labels:
    app: ff4j-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff4j-security
  template:
    metadata:
      labels:
        app: ff4j-security
    spec:
      containers:
        - name: ff4j-security
          image: lucasnscr/ff4j-security:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_url
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_password