apiVersion: v1
kind: Service
metadata:
  name: ff4j-security
  labels:
    run: ff4j-security
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: NodePort
  selector:
    app: ff4j-security